import { type NextPage } from "next";
import Head from "next/head";

import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { RouterOutputs, api } from "@/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage, LoadingSpinner } from "@/components/loading";
import { useState } from "react";

dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className="flex gap-3 border-b border-slate-400 p-8">
      <Image
        src={author.profileImageUrl}
        alt="avatar"
        width="52"
        height="52"
        className="h-14 w-14 rounded-full"
      />
      <div className="flex flex-col gap-1">
        <div className="flex gap-1">
          {!!author.username && <span>{`@${author.username}`}</span>}
          <span>{` - ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <div className="text-xl">{post.content}</div>
      </div>
    </div>
  );
};

const CreatePostWizard = () => {
  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
  });

  const [input, setInput] = useState("");

  const user = useUser();
  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <UserButton />
      <input
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button onClick={() => mutate({ content: input })} disabled={isPosting}>
        Post
      </button>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postLoading } = api.posts.getAll.useQuery();

  if (postLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <div className="flex flex-col">
      {data?.map((fullpost) => (
        <PostView {...fullpost} key={fullpost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching asap (using caching)
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-8">
            {!isSignedIn ? <SignInButton /> : <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
