import { type NextPage } from "next";
import Head from "next/head";

import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { RouterOutputs, api } from "@/utils/api";
import Image from "next/image";

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className="flex gap-3 border-b border-slate-400 p-8">
      <Image
        src={author.profileImageUrl}
        alt="avatar"
        width="52"
        height="52"
        className="h-14 w-14 rounded-full"
      />
      <div className="flex flex-col gap-1">
        {!!author.username && <span>{`@${author.username}`}</span>}
        <div>{post.content}</div>
      </div>
    </div>
  );
};

const CreatePostWizard = () => {
  const user = useUser();
  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <UserButton />
      <input
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-8">
            {!user.isSignedIn ? <SignInButton /> : <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullpost) => (
              <PostView {...fullpost} key={fullpost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
